### ISSUE TITLE
Texte barré

### ISSUE THREAD

**Issue by martinqt** [Luthaf/Zested#5]
La prévisualisation ne barre pas le texte : ainsi `~~test~~` est affiché `test`.

Bravo pour ce logiciel. Je me permet juste une petite question, pourquoi PySide, qui ne semble plus être mis à jour, au lieu de PyQt ?

**Comment by Luthaf** [comment]
Je regarderai ça !

> Je me permet juste une petite question, pourquoi PySide, qui ne semble plus être mis à jour, au lieu de PyQt ?

Parce que seul PySide était compatible Python3 quand j'avais regardé. Il faudrait que je refasse les recherches aujourd'hui.

**Comment by martinqt** [comment]
J'ai oublié, je suis sous windows, on sait jamais. 

Je n'ai fait que survoler le sujet, mais apparemment il y a quelques options en plus : http://askubuntu.com/questions/339723/can-i-sell-my-pyqt4-app-without-having-a-pyqt-license. En gros ca pointe vers ce fichier (https://github.com/Werkov/PyQt4/blob/master/GPL_EXCEPTION.TXT#L38) qui semble autoriser d'autres licences. Ce n'est pas le dépôt officiel, mais ça peut être une piste. Après c'était plus dans une perspective d'évolution future plus ou moins lointaine que je me posais cette question.
